const peso1 = Number(prompt("Digite o peso da pessoa 1:"))
const peso2 = Number(prompt("Digite o peso da pessoa 2:"))
const peso3 = Number(prompt("Digite o peso da pessoa 3:"))
const peso4 = Number(prompt("Digite o peso da pessoa 4:"))
const peso5 = Number(prompt("Digite o peso da pessoa 5:"))
const resultado = (peso1 + peso2 + peso3 + peso4 + peso5)
alert(resultado)